Adding mountpoint variable into the required options passed and the jq tool to parse it out

diff --git a/assets/check b/assets/check
--- a/assets/check
+++ b/assets/check
@@ -7,41 +7,51 @@ cat > $PAYLOAD <&0
 SCRIPT_INPUT_JSON=`cat $PAYLOAD`
 echo $SCRIPT_INPUT_JSON 1>&2
 
+MOUNTPOINT=$(jq -r '.source.mountpoint // ""' < $PAYLOAD)
+echo $MOUNTPOINT 1>&2
+
 if [ -e $CONCOURSE_SHARE_BASE ]; then
 
-  VERSION=`python -c "d = ${SCRIPT_INPUT_JSON}; print d['version']['ref']"`
+  mount -o resvport  $MOUNTPOINT $CONCOURSE_SHARE_BASE
   if [ $? -eq 0 ]; then
-    echo $VERSION 1>&2
 
-    REFS=''
-    for DIR in `ls -1t $CONCOURSE_SHARE_BASE`; do
-      echo $DIR 1>&2
-
-      NEW_REF="{ \"ref\": \"$DIR\" },"
-      REFS=$NEW_REF$REFS # See the concat
-
-      if [ $DIR = $VERSION ]; then
-        break
-      fi
-    done
-
-    OUTPUT_STRING="[ $REFS ]"
-    echo $OUTPUT_STRING
-    exit 0
-  else
-    # If we are here then the python Failed. This probebly implies the
-    # version was no present, so we retuen the current version if any
-    echo "Falling back to return current version" 1>&2
-
-    VERSION=`s -1t | head -1`
-    OUTPUT_STRING="[]"
+    VERSION=`python -c "d = ${SCRIPT_INPUT_JSON}; print d['version']['ref']"`
     if [ $? -eq 0 ]; then
-      REFS="{ \"ref\": \"$VERSION\" }"
-      OUTPUT_STRING="[ $REFS ]"
-    fi
-    echo $OUTPUT_STRING
-    exit 0
+      echo $VERSION 1>&2
 
+      REFS=''
+      for DIR in `ls -1t $CONCOURSE_SHARE_BASE`; do
+        echo $DIR 1>&2
+
+        NEW_REF="{ \"ref\": \"$DIR\" },"
+        REFS=$NEW_REF$REFS # See the concat
+
+        if [ $DIR = $VERSION ]; then
+          break
+        fi
+      done
+
+      OUTPUT_STRING="[ $REFS ]"
+      echo $OUTPUT_STRING
+      exit 0
+    else
+      # If we are here then the python Failed. This probebly implies the
+      # version was no present, so we retuen the current version if any
+      echo "Falling back to return current version" 1>&2
+
+      VERSION=`s -1t | head -1`
+      OUTPUT_STRING="[]"
+      if [ $? -eq 0 ]; then
+        REFS="{ \"ref\": \"$VERSION\" }"
+        OUTPUT_STRING="[ $REFS ]"
+      fi
+      echo $OUTPUT_STRING
+      exit 0
+
+    fi
+  else
+    echo "Fail to mount $MOUNTPOINT on $CONCOURSE_SHARE_BASE"
+    exit 1
   fi
 
 else
diff --git a/assets/in b/assets/in
--- a/assets/in
+++ b/assets/in
@@ -14,32 +14,41 @@ cat > $PAYLOAD <&0
 SCRIPT_INPUT_JSON=`cat $PAYLOAD`
 echo $SCRIPT_INPUT_JSON 1>&2
 
+MOUNTPOINT=$(jq -r '.source.mountpoint // ""' < $PAYLOAD)
+echo $MOUNTPOINT 1>&2
+
 if [ -e $CONCOURSE_SHARE_BASE ]; then
 
-  VERSION=`python -c "d = ${SCRIPT_INPUT_JSON}; print d['version']['ref']"`
+  mount -o resvport  $MOUNTPOINT $CONCOURSE_SHARE_BASE
   if [ $? -eq 0 ]; then
-    echo $VERSION 1>&2
 
-    SRC_DIR=$CONCOURSE_SHARE_BASE/$VERSION
-    echo $SRC_DIR 2>&1
+    VERSION=`python -c "d = ${SCRIPT_INPUT_JSON}; print d['version']['ref']"`
+    if [ $? -eq 0 ]; then
+      echo $VERSION 1>&2
 
-    if [ -d $SRC_DIR ]; then
-      RSYNC_CMD="rsync -av $SRC_DIR $DEST_DIR 1>&2"
-      echo $RSYNC_CMD 1>&2
-      eval $RSYNC_CMD
-      if [ $? -eq 0 ]; then
-          OUTPUT_STRING="{ \"version\": { \"ref\": \"$MD5_STRING\"} }"
-          echo $OUTPUT_STRING
-          exit 0
+      SRC_DIR=$CONCOURSE_SHARE_BASE/$VERSION
+      echo $SRC_DIR 2>&1
+
+      if [ -d $SRC_DIR ]; then
+        RSYNC_CMD="rsync -av $SRC_DIR $DEST_DIR 1>&2"
+        echo $RSYNC_CMD 1>&2
+        eval $RSYNC_CMD
+        if [ $? -eq 0 ]; then
+            OUTPUT_STRING="{ \"version\": { \"ref\": \"$MD5_STRING\"} }"
+            echo $OUTPUT_STRING
+            exit 0
+        else
+          echo "Failed to rsync $SRC_DIR to $DEST_DIR" 1>&2
+          exit 1
+        fi
       else
-        echo "Failed to rsync $SRC_DIR to $DEST_DIR" 1>&2
+        echo "Version $VERSION no longer available in $CONCOURSE_SHARE_BASE" 1>&2
         exit 1
       fi
     else
-      echo "Version $VERSION no longer available in $CONCOURSE_SHARE_BASE" 1>&2
+      echo "Fail to mount $MOUNTPOINT on $CONCOURSE_SHARE_BASE"
       exit 1
     fi
-
   else
     echo "Cannot determine verson to fetch!" 1>&2
     exit 1
diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -22,40 +22,49 @@ cat > $PAYLOAD <&0
 SCRIPT_INPUT_JSON=`cat $PAYLOAD`
 echo $SCRIPT_INPUT_JSON 1>&2
 
+MOUNTPOINT=$(jq -r '.source.mountpoint // ""' < $PAYLOAD)
+echo $MOUNTPOINT 1>&2
+
 if [ -e $CONCOURSE_SHARE_BASE ]; then
 
-  VERSION_STRING="$BUILD_PIPELINE_NAME-$BUILD_ID"
-
-  echo $VERSION_STRING 1>&2
-
-  MD5_STRING=`echo $VERSION_STRING | $MD5_TOOL | cut -d ' ' -f 1 `
+  mount -o resvport  $MOUNTPOINT $CONCOURSE_SHARE_BASE
   if [ $? -eq 0 ]; then
-    echo $MD5_STRING 1>&2
 
-    # Create the new directory for this build
-    DEST_DIR=$CONCOURSE_SHARE_BASE/$MD5_STRING
-    echo $DEST_DIR 1>&2
+    VERSION_STRING="$BUILD_PIPELINE_NAME-$BUILD_ID"
 
-    mkdir -p $DEST_DIR
+    echo $VERSION_STRING 1>&2
 
+    MD5_STRING=`echo $VERSION_STRING | $MD5_TOOL | cut -d ' ' -f 1 `
     if [ $? -eq 0 ]; then
-      RSYNC_CMD="rsync -av $SRC_DIR $DEST_DIR 1>&2"
-      echo $RSYNC_CMD 1>&2
+      echo $MD5_STRING 1>&2
 
-      eval $RSYNC_CMD
+      # Create the new directory for this build
+      DEST_DIR=$CONCOURSE_SHARE_BASE/$MD5_STRING
+      echo $DEST_DIR 1>&2
+
+      mkdir -p $DEST_DIR
+
       if [ $? -eq 0 ]; then
-          OUTPUT_STRING="{ \"version\": { \"ref\": \"$MD5_STRING\"} }"
-          echo $OUTPUT_STRING
-          exit 0
+        RSYNC_CMD="rsync -av $SRC_DIR $DEST_DIR 1>&2"
+        echo $RSYNC_CMD 1>&2
+
+        eval $RSYNC_CMD
+        if [ $? -eq 0 ]; then
+            OUTPUT_STRING="{ \"version\": { \"ref\": \"$MD5_STRING\"} }"
+            echo $OUTPUT_STRING
+            exit 0
+        else
+          echo "Failed to rsync $SRC_DIR to $DEST_DIR" 1>&2
+          exit 1
+        fi
       else
-        echo "Failed to rsync $SRC_DIR to $DEST_DIR" 1>&2
+        echo "Failed to create destination $DEST_DIR" 1>&2
         exit 1
       fi
     else
-      echo "Failed to create destination $DEST_DIR" 1>&2
+      echo "Fail to mount $MOUNTPOINT on $CONCOURSE_SHARE_BASE"
       exit 1
     fi
-
   else
     echo "Failed to create MD5 hash"
     exit 1
