Implement in asset

diff --git a/assets/in b/assets/in
--- a/assets/in
+++ b/assets/in
@@ -1,10 +1,54 @@
 #!/usr/bin/env bash
 
 DEST_DIR=$1
-
+CONCOURSE_SHARE_BASE='/mnt/concourse_share'
 echo $DEST_DIR
 echo $BUILD_ID
 echo $BUILD_NAME
 echo $BUILD_JOB_NAME
 echo $BUILD_PIPELINE_NAME
 echo $ATC_EXTERNAL_URL
+
+SCRIPT_INPUT_JSON=''
+while read LINE
+do
+  SCRIPT_INPUT_JSON=$SCRIPT_INPUT_JSON$LINE
+done
+
+echo $SCRIPT_INPUT_JSON 1>&2
+
+
+if [ -e $CONCOURSE_SHARE_BASE ]; then
+
+  VERSION=`python -c "d = ${SCRIPT_INPUT_JSON}; print d['version']['ref']"`
+  if [ $? -eq 0 ]; then
+    echo $VERSION 1>&2
+
+    SRC_DIR=$CONCOURSE_SHARE_BASE/$VERSION
+    echo $SRC_DIR 2>&1
+
+    if [ -d $SRC_DIR ]; then
+      RSYNC_CMD="rsync -av $SRC_DIR $DEST_DIR 1>&2"
+      echo $RSYNC_CMD 1>&2
+      eval $RSYNC_CMD
+      if [ $? -eq 0 ]; then
+          OUTPUT_STRING="{ \"version\": { \"ref\": \"$MD5_STRING\"} }"
+          echo $OUTPUT_STRING
+          exit 0
+      else
+        echo "Failed to rsync $SRC_DIR to $DEST_DIR" 1>&2
+        exit 1
+      fi      
+    else
+      echo "Version $VERSION no longer available in $CONCOURSE_SHARE_BASE" 1>&2
+      exit 1
+    fi
+
+  else
+    echo "Cannot determine verson to fetch!" 1>&2
+    exit 1
+  fi
+else
+  echo "No /mnt/concourse_share directory found" 1>&2
+  exit 1
+fi
