replace MD5 with timestamp

diff --git a/assets/in b/assets/in
--- a/assets/in
+++ b/assets/in
@@ -9,12 +9,6 @@ echo $BUILD_PIPELINE_NAME 1>&2
 echo $ATC_EXTERNAL_URL 1>&2
 
 PLATFORM=`uname`
-MD5_TOOL="md5sum"
-if [ $PLATFORM = "Darwin" ]; then
-  MD5_TOOL="md5"
-fi
-
-echo $MD5_TOOL 1>&2
 
 SCRIPT_INPUT='/tmp/input'
 cat > $SCRIPT_INPUT <&0 # STDIN params
@@ -50,6 +44,7 @@ SSH_ASKPASS=/opt/resource/askpass.sh DISPLAY= ssh-add ~/.ssh/server_key 1>&2 >/d
 
 if [ $DISABLE_VERSION_PATH -eq 0 ]
 then
+    # any version is already rolled in
     SRC_DIR=$BASE_DIR
 else
     SRC_DIR=$BASE_DIR/$VERSION
@@ -57,8 +52,8 @@ fi
 
 echo $SRC_DIR 1>&2
 
-if [ -z "$VERSION" ]; then
-  echo "ERROR Version specifiation $VERSION invalid!"
+if [ -z "$VERSION" && $DISABLE_VERSION_PATH -eq 1 ]; then
+  echo "ERROR Version specification $VERSION invalid!" 1>&2
   exit 1
 else
   if (ssh -t -i ~/.ssh/server_key -p $PORT $USER@$SERVER '[ -d $SRC_DIR ]' ); then
@@ -66,7 +61,8 @@ else
     echo $RSYNC_CMD  1>&2
     eval $RSYNC_CMD  1>&2
     if [ $? -eq 0 ]; then
-        OUTPUT_STRING="{ \"version\": { \"ref\": \"$MD5_STRING\"} }"
+        TIMESTAMP=$(find $DEST_DIR -type f -exec stat -c "%Y" {} \; | sort -n | tail -1)
+        OUTPUT_STRING="{ \"version\": { \"ref\": \"$TIMESTAMP\"} }"
         echo $OUTPUT_STRING
         exit 0
     else
@@ -74,7 +70,7 @@ else
       exit 1
     fi
   else
-    echo "Version $VERSION no longer available in $BASE_DIR"
+    echo "Version $VERSION no longer available in $BASE_DIR" 1>&2
     exit 1
   fi
 fi
diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -61,53 +61,39 @@ chmod -R 600 ~/.ssh
 eval $(ssh-agent) 1>&2 2>/dev/null
 SSH_ASKPASS=/opt/resource/askpass.sh DISPLAY= ssh-add ~/.ssh/server_key 1>&2 2>/dev/null
 
-VERSION_STRING="$BUILD_PIPELINE_NAME-$BUILD_ID"
-echo $VERSION_STRING 1>&2
+TIMESTAMP=$(find "$SRC_DIR/$SYNC_DIR" -type f -exec stat -c "%Y" {} \; | sort -n | tail -1)
+echo "DEBUG: Timestamp of latest modified file is $TIMESTAMP" 1>&2
 
-MD5_STRING=`echo $VERSION_STRING | $MD5_TOOL | cut -d ' ' -f 1 `
-if [ $? -eq 0 ]; then
-  echo $MD5_STRING 1>&2
-  
-  if [ $DISABLE_VERSION_PATH -eq 0 ]
-  then
-      MD5_PATH=""
-  else
-      MD5_PATH=$MD5_STRING
-  fi
+# Create the new directory for this build
+DEST_DIR=$BASE_DIR/$TIMESTAMP
+echo $DEST_DIR 1>&2
 
-  # Create the new directory for this build
-  DEST_DIR=$BASE_DIR/$MD5_PATH
-  echo $DEST_DIR 1>&2
-  
-  REPORTED_VERSION=0
-  for SERVER in $SERVERS
-  do
-      CMD="ssh -i ~/.ssh/server_key -p $PORT $USER@$SERVER mkdir -p $DEST_DIR"
-      echo $CMD 1>&2
-      eval $CMD 1>&2
-      
-      if [ $? -eq 0 ]; then
-        RSYNC_CMD="rsync $RSYNC_OPTS -e 'ssh -i ~/.ssh/server_key -p $PORT'  $SRC_DIR/$SYNC_DIR/ $USER@$SERVER:$DEST_DIR"
-        echo $RSYNC_CMD 1>&2
+REPORTED_VERSION=0
+for SERVER in $SERVERS
+do
+    CMD="ssh -i ~/.ssh/server_key -p $PORT $USER@$SERVER mkdir -p $DEST_DIR"
+    echo $CMD 1>&2
+    eval $CMD 1>&2
 
-        eval $RSYNC_CMD  1>&2
-        if [ $? -eq 0 ]; then
-            if [ $REPORTED_VERSION -eq 0 ]
-            then
-                OUTPUT_STRING="{ \"version\": { \"ref\": \"$MD5_STRING\"} }"
-                echo $OUTPUT_STRING
-                REPORTED_VERSION=1
-            fi
-        else
-          echo "Failed to rsync $SRC_DIR to $DEST_DIR" 1>&2
-          exit 1
+    if [ $? -eq 0 ]; then
+    RSYNC_CMD="rsync $RSYNC_OPTS -e 'ssh -i ~/.ssh/server_key -p $PORT'  $SRC_DIR/$SYNC_DIR/ $USER@$SERVER:$DEST_DIR"
+    echo $RSYNC_CMD 1>&2
+
+    eval $RSYNC_CMD  1>&2
+    if [ $? -eq 0 ]; then
+        if [ $REPORTED_VERSION -eq 0 ]
+        then
+            OUTPUT_STRING="{ \"version\": { \"ref\": \"$TIMESTAMP\"} }"
+            echo "DEBUG: outputting $OUTPUT_STRING to concourse" 1>&2
+            echo $OUTPUT_STRING
+            REPORTED_VERSION=1
         fi
-      else
-        echo "Failed to create destination $DEST_DIR" 1>&2
+    else
+        echo "Failed to rsync $SRC_DIR to $DEST_DIR" 1>&2
         exit 1
-      fi
-  done
-else
-  echo "Failed to create MD5 hash" 1>&2
-  exit 1
-fi
+    fi
+    else
+    echo "Failed to create destination $DEST_DIR" 1>&2
+    exit 1
+    fi
+done
