Additional debug and error if version passed to in is not valid

diff --git a/assets/in b/assets/in
--- a/assets/in
+++ b/assets/in
@@ -31,10 +31,12 @@ if [ -z "$PORT" ]; then
     PORT=22
 fi
 
+echo $SCRIPT_INPUT 1>&2
 echo $SERVER    1>&2
 echo $PORT      1>&2
 echo $BASE_DIR  1>&2
 echo $USER      1>&2
+echo $VERSION   1>&2
 
 mkdir ~/.ssh
 chmod 600 ~/.ssh
@@ -48,19 +50,24 @@ SSH_ASKPASS=/opt/resource/askpass.sh DISPLAY= ssh-add ~/.ssh/server_key 1>&2 >/d
 SRC_DIR=$BASE_DIR/$VERSION
 echo $SRC_DIR 1>&2
 
-if (ssh -t -i ~/.ssh/server_key -p $PORT $USER@$SERVER '[ -d $SRC_DIR ]' ); then
-  RSYNC_CMD="rsync -Pav -e 'ssh -i ~/.ssh/server_key -p $PORT' $USER@$SERVER:$SRC_DIR/* $DEST_DIR"
-  echo $RSYNC_CMD  1>&2
-  eval $RSYNC_CMD  1>&2
-  if [ $? -eq 0 ]; then
-      OUTPUT_STRING="{ \"version\": { \"ref\": \"$MD5_STRING\"} }"
-      echo $OUTPUT_STRING
-      exit 0
+if [ -z "$VERSION" ]; then
+  echo "ERROR Version specifiation $VERSION invalid!"
+  exit 1
+else
+  if (ssh -t -i ~/.ssh/server_key -p $PORT $USER@$SERVER '[ -d $SRC_DIR ]' ); then
+    RSYNC_CMD="rsync -Pav -e 'ssh -i ~/.ssh/server_key -p $PORT' $USER@$SERVER:$SRC_DIR/* $DEST_DIR"
+    echo $RSYNC_CMD  1>&2
+    eval $RSYNC_CMD  1>&2
+    if [ $? -eq 0 ]; then
+        OUTPUT_STRING="{ \"version\": { \"ref\": \"$MD5_STRING\"} }"
+        echo $OUTPUT_STRING
+        exit 0
+    else
+      echo "Failed to rsync $SRC_DIR to $DEST_DIR" 1>&2
+      exit 1
+    fi
   else
-    echo "Failed to rsync $SRC_DIR to $DEST_DIR" 1>&2
+    echo "Version $VERSION no longer available in $BASE_DIR"
     exit 1
   fi
-else
-  echo "Version $VERSION no longer available in $BASE_DIR"
-  exit 1
 fi
