Adjust debug in out and in

diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -1,16 +1,12 @@
 #!/usr/bin/env bash
 
-exec 3>&1 # stdout on fd3
-exec 1>&2 # all other ouput to stderr
-
-
 SRC_DIR=$1
-echo $SRC_DIR
-echo $BUILD_ID
-echo $BUILD_NAME
-echo $BUILD_JOB_NAME
-echo $BUILD_PIPELINE_NAME
-echo $ATC_EXTERNAL_URL
+echo $SRC_DIR 1>&2
+echo $BUILD_ID 1>&2
+echo $BUILD_NAME 1>&2
+echo $BUILD_JOB_NAME 1>&2
+echo $BUILD_PIPELINE_NAME 1>&2
+echo $ATC_EXTERNAL_URL 1>&2
 
 PLATFORM=`uname`
 MD5_TOOL="md5sum"
@@ -18,7 +14,7 @@ if [ $PLATFORM = "Darwin" ]; then
   MD5_TOOL="md5"
 fi
 
-echo $MD5_TOOL
+echo $MD5_TOOL 1>&2
 
 SCRIPT_INPUT='/tmp/input'
 cat > $SCRIPT_INPUT <&0 # STDIN params
@@ -27,9 +23,9 @@ SERVER=$(jq -r '.source.server // ""' < $SCRIPT_INPUT)
 BASE_DIR=$(jq -r '.source.base_dir // ""' < $SCRIPT_INPUT)
 USER=$(jq -r '.source.user // ""' < $SCRIPT_INPUT)
 
-echo $SERVER
-echo $BASE_DIR
-echo $USER
+echo $SERVER 1>&2
+echo $BASE_DIR 1>&2
+echo $USER 1>&2
 
 mkdir ~/.ssh
 chmod 600 ~/.ssh
@@ -37,50 +33,42 @@ chmod 600 ~/.ssh
 echo -e "Host $SERVER\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
 chmod 600 ~/.ssh/*
 
-eval $(ssh-agent) >/dev/null
-SSH_ASKPASS=/opt/resource/askpass.sh DISPLAY= ssh-add ~/.ssh/server_key >/dev/null
+eval $(ssh-agent) 1>&2 2>/dev/null
+SSH_ASKPASS=/opt/resource/askpass.sh DISPLAY= ssh-add ~/.ssh/server_key 1>&2 2>/dev/null
 
-if [ -e $CONCOURSE_SHARE_BASE ]; then
+VERSION_STRING="$BUILD_PIPELINE_NAME-$BUILD_ID"
+echo $VERSION_STRING 1>&2
 
-  VERSION_STRING="$BUILD_PIPELINE_NAME-$BUILD_ID"
+MD5_STRING=`echo $VERSION_STRING | $MD5_TOOL | cut -d ' ' -f 1 `
+if [ $? -eq 0 ]; then
+  echo $MD5_STRING 1>&2
 
-  echo $VERSION_STRING
+  # Create the new directory for this build
+  DEST_DIR=$BASE_DIR/$MD5_STRING
+  echo $DEST_DIR 1>&2
 
-  MD5_STRING=`echo $VERSION_STRING | $MD5_TOOL | cut -d ' ' -f 1 `
+  CMD="ssh -i ~/.ssh/server_key $USER@$SERVER mkdir -p $DEST_DIR"
+  echo $CMD 1>&2
+  eval $CMD 1>&2
+
   if [ $? -eq 0 ]; then
-    echo $MD5_STRING
+    RSYNC_CMD="rsync -Pav -e 'ssh -i ~/.ssh/server_key'  $SRC_DIR $USER@$SERVER:$DEST_DIR"
+    echo $RSYNC_CMD 1>&2
 
-    # Create the new directory for this build
-    DEST_DIR=$BASE_DIR/$MD5_STRING
-    echo $DEST_DIR
-
-    CMD="ssh -i ~/.ssh/server_key $USER@$SERVER mkdir -p $DEST_DIR"
-    echo $CMD
-    eval $CMD
-
+    eval $RSYNC_CMD  1>&2
     if [ $? -eq 0 ]; then
-      RSYNC_CMD="rsync -Pav -e 'ssh -i ~/.ssh/server_key'  $SRC_DIR $USER@$SERVER:$DEST_DIR"
-      echo $RSYNC_CMD
-
-      eval $RSYNC_CMD
-      if [ $? -eq 0 ]; then
-          OUTPUT_STRING="{ \"version\": { \"ref\": \"$MD5_STRING\"} }"
-          echo $OUTPUT_STRING >&3
-          exit 0
-      else
-        echo "Failed to rsync $SRC_DIR to $DEST_DIR"
-        exit 1
-      fi
+        OUTPUT_STRING="{ \"version\": { \"ref\": \"$MD5_STRING\"} }"
+        echo $OUTPUT_STRING
+        exit 0
     else
-      echo "Failed to create destination $DEST_DIR"
+      echo "Failed to rsync $SRC_DIR to $DEST_DIR" 1>&2
       exit 1
     fi
   else
-    echo "Failed to create MD5 hash"
+    echo "Failed to create destination $DEST_DIR" 1>&2
     exit 1
   fi
-
 else
-  echo "No /mnt/concourse_share directory found"
+  echo "Failed to create MD5 hash" 1>&2
   exit 1
 fi
